/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Repository.SanPhamRepository;
import domainmodel.ChiTietSP;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.SanPham;
import model.SanPham2;

/**
 *
 * @author c
 */
public class SanPhamView extends javax.swing.JFrame {

    SanPhamRepository rs = new SanPhamRepository();
    DefaultTableModel dtm = new DefaultTableModel();
    DefaultTableModel dtm2 = new DefaultTableModel();
    private List<SanPham> nvlist = new ArrayList<>();
    private List<SanPham2> nvlist2 = new ArrayList<>();

    /**
     * Creates new form SanPhamView
     */
    public SanPhamView() {
        initComponents();
        tbtable.setModel(dtm = new DefaultTableModel());
        String[] heder = {"mã sản phẩm", "Tên sản phẩm", "đơn giá", "số lượng", "dòng sp", "size", "trang thái", "màu sắc"};
        dtm.setColumnIdentifiers(heder);
        nvlist = rs.getall();
        showdatatable(nvlist);
        tbtable2.setModel(dtm2 = new DefaultTableModel());
        String[] heder1 = {"mã sản phẩm", "tên sản phẩm", "số lượng"};
        dtm2.setColumnIdentifiers(heder1);
        nvlist2 = rs.getallsp();
        showdatatable2(nvlist2);
    }

    public void showdatatable(List<SanPham> sp) {
        dtm.setRowCount(0);
        for (SanPham thongkeViewModel : sp) {
            dtm.addRow(thongkeViewModel.showdatatable());
        }
    }

    public void showdatatable2(List<SanPham2> sp) {
        dtm2.setRowCount(0);
        for (SanPham2 sanPham : sp) {
            dtm2.addRow(sanPham.getdatatble());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtgiasp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbdongsp = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbsize = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbmau = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbtrangthai = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbtable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtmasp2 = new javax.swing.JTextField();
        txttensp2 = new javax.swing.JTextField();
        txtsoluongsp2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btnthem2 = new javax.swing.JButton();
        btnxoa2 = new javax.swing.JButton();
        btncapnhat2 = new javax.swing.JButton();
        lblma = new javax.swing.JLabel();
        lblten = new javax.swing.JLabel();
        lblsoluong = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sản Phẩm chi tiết"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ma sp");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 37, -1));

        jLabel2.setText("ten sp");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 56, 37, -1));

        jLabel3.setText("gia sp");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 85, 37, -1));
        jPanel1.add(txtgiasp, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 82, 237, -1));

        jLabel4.setText("soluong");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 114, -1, -1));

        jLabel5.setText("dòng sp");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 21, -1, -1));

        cbdongsp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "quan", "ao" }));
        jPanel1.add(cbdongsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 18, 231, -1));

        jLabel6.setText("size");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 56, 37, -1));

        cbsize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jPanel1.add(cbsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 53, 231, -1));

        jLabel7.setText("màu");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 85, 37, -1));

        cbmau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "xanh", "do", "tim", "vang" }));
        jPanel1.add(cbmau, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 82, 231, -1));

        jLabel8.setText("trạng thái");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 123, -1, -1));

        cbtrangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        jPanel1.add(cbtrangthai, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 120, 231, -1));

        jButton1.setText("clear");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 164, -1, -1));

        btnxoa.setText("xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnxoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 164, -1, -1));

        btnthem.setText("thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });
        jPanel1.add(btnthem, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 164, -1, -1));

        btnupdate.setText("cập nhật");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 164, -1, -1));

        tbtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbtable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 207, 988, 169));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Sản Phẩm"));

        tbtable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbtable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbtable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbtable2);

        jLabel9.setText("ma sp");

        jLabel10.setText("ten sp");

        jLabel11.setText("so luong sp");

        txttensp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttensp2ActionPerformed(evt);
            }
        });

        jButton3.setText("clear");

        btnthem2.setText("thêm");
        btnthem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthem2ActionPerformed(evt);
            }
        });

        btnxoa2.setText("xóa");
        btnxoa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoa2ActionPerformed(evt);
            }
        });

        btncapnhat2.setText("cập nhật");
        btncapnhat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhat2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsoluongsp2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmasp2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttensp2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnthem2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnxoa2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncapnhat2)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtmasp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txttensp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtsoluongsp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(btnthem2)
                            .addComponent(btnxoa2)
                            .addComponent(btncapnhat2))
                        .addGap(43, 43, 43))))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 1030, 240));

        lblma.setText("-");
        jPanel1.add(lblma, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 140, -1));

        lblten.setText("-");
        jPanel1.add(lblten, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 170, -1));

        lblsoluong.setText("-");
        jPanel1.add(lblsoluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 170, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(455, 455, 455)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        if (lblma.getText() == "-" && lblsoluong.getText() == "-" && lblten.getText() == "-") {
            JOptionPane.showMessageDialog(rootPane, "Thêm thất bại do bạn cần chọn ở mục sản phẩm để thêm chit tiết sản phẩm");
        } else {
            String ma = lblma.getText();
            String name = lblten.getText();
            int soluong = Integer.parseInt(lblsoluong.getText());
            Double gia = Double.parseDouble(txtgiasp.getText());
            String dongsp = cbdongsp.getSelectedItem().toString();
            String mau = cbmau.getSelectedItem().toString();
            String size = cbsize.getSelectedItem().toString();
            int trangthai = Integer.parseInt(cbtrangthai.getSelectedItem().toString());
            rs.add(size, name, mau, dongsp, new ChiTietSP(null, null, null, null, null, null, null, null, gia, trangthai));
            nvlist = rs.getall();
            showdatatable(nvlist);
            JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void txttensp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttensp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttensp2ActionPerformed

    private void tbtable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbtable2MouseClicked
        // TODO add your handling code here:
        int row = tbtable2.getSelectedRow();
        lblma.setText(tbtable2.getValueAt(row, 0).toString());
        lblten.setText(tbtable2.getValueAt(row, 1).toString());
        lblsoluong.setText(tbtable2.getValueAt(row, 2).toString());
    }//GEN-LAST:event_tbtable2MouseClicked

    private void btnthem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthem2ActionPerformed
        // TODO add your handling code here:
        String ma = txtmasp2.getText();
        String ten = txttensp2.getText();
        String soluong = txtsoluongsp2.getText();
        if (ma == "" && ten == "" && soluong == "") {
            JOptionPane.showMessageDialog(rootPane, "Thêm thất bại do các trường dữ liệu chưa được nhập");
        } else {
            rs.addsanpham(new SanPham2(ma, ten, soluong));
            nvlist2 = rs.getallsp();
            showdatatable2(nvlist2);
            JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
        }
    }//GEN-LAST:event_btnthem2ActionPerformed

    private void btnxoa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoa2ActionPerformed
        // TODO add your handling code here:
        try {
            SanPham2 dv = nvlist2.get(tbtable2.getSelectedRow());
            rs.delete(dv.getMa());
            nvlist2 = rs.getallsp();
            showdatatable2(nvlist2);
            JOptionPane.showMessageDialog(rootPane, "xóa thành công");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "xóa thất bại bạn cần phải chọn mục muốn xóa ở table");
        }

    }//GEN-LAST:event_btnxoa2ActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        try {
            SanPham dv = nvlist.get(tbtable.getSelectedRow());
            rs.deletechitiet(dv.getId());
            nvlist = rs.getall();
            showdatatable(nvlist);
            JOptionPane.showMessageDialog(rootPane, "xóa thành công");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "xóa thất bại bạn cần phải chọn mục muốn xóa ở table");
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        SanPham dv = nvlist.get(tbtable.getSelectedRow());
        String ma = lblma.getText();
        String name = lblten.getText();
        int soluong = Integer.parseInt(lblsoluong.getText());
        Double gia = Double.parseDouble(txtgiasp.getText());
        String dongsp = cbdongsp.getSelectedItem().toString();
        String mau = cbmau.getSelectedItem().toString();
        String size = cbsize.getSelectedItem().toString();
        int trangthai = Integer.parseInt(cbtrangthai.getSelectedItem().toString());
        rs.update(size, name, mau, dongsp, new ChiTietSP(null, null, null, null, null, null, null, null, gia, trangthai), dv.getId());
        nvlist = rs.getall();
        showdatatable(nvlist);
        JOptionPane.showMessageDialog(rootPane, "update thành công");
    }//GEN-LAST:event_btnupdateActionPerformed

    private void tbtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbtableMouseClicked
        // TODO add your handling code here:
        int row = tbtable.getSelectedRow();
        lblma.setText(tbtable.getValueAt(row, 0).toString());
        lblten.setText(tbtable.getValueAt(row, 1).toString());
        txtgiasp.setText(tbtable.getValueAt(row, 2).toString());
        lblsoluong.setText(tbtable.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tbtableMouseClicked

    private void btncapnhat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapnhat2ActionPerformed
        // TODO add your handling code here:
        SanPham2 dv = nvlist2.get(tbtable2.getSelectedRow());
        String ma = txtmasp2.getText();
        String ten = txttensp2.getText();
        String soluong = txtsoluongsp2.getText();
        rs.update(new SanPham2(ma, ten, soluong),dv.getMa());
        nvlist2 = rs.getallsp();
        showdatatable2(nvlist2);
        JOptionPane.showMessageDialog(rootPane, "update thành công");
    }//GEN-LAST:event_btncapnhat2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPhamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPhamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPhamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPhamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SanPhamView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncapnhat2;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnthem2;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btnxoa;
    private javax.swing.JButton btnxoa2;
    private javax.swing.JComboBox<String> cbdongsp;
    private javax.swing.JComboBox<String> cbmau;
    private javax.swing.JComboBox<String> cbsize;
    private javax.swing.JComboBox<String> cbtrangthai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblma;
    private javax.swing.JLabel lblsoluong;
    private javax.swing.JLabel lblten;
    private javax.swing.JTable tbtable;
    private javax.swing.JTable tbtable2;
    private javax.swing.JTextField txtgiasp;
    private javax.swing.JTextField txtmasp2;
    private javax.swing.JTextField txtsoluongsp2;
    private javax.swing.JTextField txttensp2;
    // End of variables declaration//GEN-END:variables
}
